### ISSUE TITLE
What about bracket users? 

### ISSUE THREAD

**Issue by Oluwasetemi** [joshbuchea/atom-html-head-snippets#2]
Is it possible to have something like this for those of us who use bracket? I love the way it works.

**Comment by joshbuchea** [comment]
@Oluwasetemi it would be excellent to have an extension for Brackets with this functionality. Unfortunately, I don't have any experience developing Brackets extensions. Would be a great project for someone to take up.

I'm going to close this issue, since what you're proposing would be a new independent project. Thanks for the suggestion @Oluwasetemi!

**Comment by Oluwasetemi** [comment]
@joshbuchea i will try to work on the project.

**Comment by joshbuchea** [comment]
@Oluwasetemi excellent!
